# The URL the site will be built for
#base_url = "https://vinicius-fernandes.github.io"
base_url= "127.0.0.1:1111"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true





[languages.pt]


[extra]
# Put all your custom variables here
author = "Vinicius Fernandes"
avatar = "images/profile.jpg"

[extra.menus]
    nav = [
    { lang = "en", data = [
       {name = "Home", url="/", icon = "bi-house" },
        { name = "Stack", url = "/stack/", icon = "bi-code-slash" },
        { name = "Blog", url = "/blog/", icon = "bi-file-earmark-text" },
        { name = "Portfolio", url = "/portfolio/", icon = "bi-briefcase-fill" }
    ] },
    { lang = "pt", data = [
         {name = "Home", url="/pt/", icon = "bi-house" },
        { name = "Stack", url = "/pt/stack/", icon = "bi-code-slash" },
        { name = "Blog", url = "/pt/blog/", icon = "bi-file-earmark-text" },
        { name = "Portfólio", url = "/pt/portfolio/", icon = "bi-briefcase-fill" }
    ] }, 
    ]

[extra.stack]
    items = [
        {icon="devicon-java-plain-wordmark"},
        {icon="devicon-javascript-plain"},
        {icon="devicon-csharp-plain-wordmark"},
        {icon="devicon-html5-plain-wordmark"},
        {icon="devicon-css3-plain-wordmark"},
        {icon="devicon-spring-plain-wordmark"},
        {icon="devicon-angularjs-plain"},
        {icon="devicon-docker-plain-wordmark"},
        
    ]

    
[extra.social]
        author_link = "https://www.linkedin.com/in/vinicius-afernandes/"
        twitter = "@user"
        links = [
            { name = "Email", url = "mailto:viniciusnandes@hotmail.com", icon = "bi-envelope-fill" },
            { name = "GitHub", url = "https://github.com/vinicius-fernandes", icon = "bi-github" },
            { name = "LinkedIn", url = "https://www.linkedin.com/in/vinicius-afernandes/", icon = "bi-linkedin" }
        ]
