# The URL the site will be built for
#base_url = "https://vinicius-fernandes.github.io"
base_url= "127.0.0.1:1111"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Vinicius Fernandes"
avatar = "images/profile.jpg"

[extra.menus]
    nav = [
        {name = "Home", url="@/_index.md", icon = "bi-house"},
        { name = "Blog", url = "@/blog/_index.md", icon = "bi-file-earmark-text" },

    ]


    
[extra.social]
        author_link = "https://author-url.com/"
        twitter = "@user"
        links = [
            { name = "Email", url = "mailto:viniciusnandes@hotmail.com", icon = "bi-envelope-fill" },
            { name = "GitHub", url = "https://github.com/vinicius-fernandes", icon = "bi-github" },
            { name = "LinkedIn", url = "https://www.linkedin.com/in/vinicius-afernandes/", icon = "bi-linkedin" }
        ]
